# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Chat_pb2 as Chat__pb2


class ChatStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.recibirMensajes = channel.unary_stream(
        '/Chat/recibirMensajes',
        request_serializer=Chat__pb2.Usuario.SerializeToString,
        response_deserializer=Chat__pb2.Mensaje.FromString,
        )
    self.enviarMensaje = channel.unary_unary(
        '/Chat/enviarMensaje',
        request_serializer=Chat__pb2.Mensaje.SerializeToString,
        response_deserializer=Chat__pb2.Empty.FromString,
        )


class ChatServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def recibirMensajes(self, request, context):
    """rpc iniciarConversacion(Conversacion) returns (Empty);
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def enviarMensaje(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'recibirMensajes': grpc.unary_stream_rpc_method_handler(
          servicer.recibirMensajes,
          request_deserializer=Chat__pb2.Usuario.FromString,
          response_serializer=Chat__pb2.Mensaje.SerializeToString,
      ),
      'enviarMensaje': grpc.unary_unary_rpc_method_handler(
          servicer.enviarMensaje,
          request_deserializer=Chat__pb2.Mensaje.FromString,
          response_serializer=Chat__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Chat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
