# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Chat.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\nChat.proto\"N\n\x07Mensaje\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06sender\x18\x02 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x02(\t\x12\x10\n\x08receiver\x18\x04 \x02(\t*\x04\x08M\x10O\"O\n\x07\x41rchivo\x12\x11\n\tcontenido\x18\x01 \x01(\x0c\x12\x0c\n\x04ruta\x18\x02 \x01(\t2#\n\x07\x61rchivo\x12\x08.Mensaje\x18M \x01(\x0b\x32\x08.Archivo\"L\n\x05Texto\x12\x11\n\tcontenido\x18\x01 \x02(\t\x12\x0f\n\x07\x65\x64itado\x18\x02 \x02(\x08\x32\x1f\n\x05texto\x12\x08.Mensaje\x18N \x01(\x0b\x32\x06.Texto\"\x1b\n\x07Usuario\x12\x10\n\x08username\x18\x01 \x02(\t\"\x19\n\x05\x45mpty\x12\x10\n\x08response\x18\x01 \x02(\t2R\n\x04\x43hat\x12\'\n\x0frecibirMensajes\x12\x08.Usuario\x1a\x08.Mensaje0\x01\x12!\n\renviarMensaje\x12\x08.Mensaje\x1a\x06.Empty')
)




_MENSAJE = _descriptor.Descriptor(
  name='Mensaje',
  full_name='Mensaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Mensaje.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='Mensaje.sender', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='Mensaje.content', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='Mensaje.receiver', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(77, 79), ],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=92,
)


_ARCHIVO = _descriptor.Descriptor(
  name='Archivo',
  full_name='Archivo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contenido', full_name='Archivo.contenido', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ruta', full_name='Archivo.ruta', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='archivo', full_name='Archivo.archivo', index=0,
      number=77, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=173,
)


_TEXTO = _descriptor.Descriptor(
  name='Texto',
  full_name='Texto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contenido', full_name='Texto.contenido', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='editado', full_name='Texto.editado', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='texto', full_name='Texto.texto', index=0,
      number=78, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=251,
)


_USUARIO = _descriptor.Descriptor(
  name='Usuario',
  full_name='Usuario',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='Usuario.username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=280,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='Empty.response', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=307,
)

DESCRIPTOR.message_types_by_name['Mensaje'] = _MENSAJE
DESCRIPTOR.message_types_by_name['Archivo'] = _ARCHIVO
DESCRIPTOR.message_types_by_name['Texto'] = _TEXTO
DESCRIPTOR.message_types_by_name['Usuario'] = _USUARIO
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mensaje = _reflection.GeneratedProtocolMessageType('Mensaje', (_message.Message,), dict(
  DESCRIPTOR = _MENSAJE,
  __module__ = 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Mensaje)
  ))
_sym_db.RegisterMessage(Mensaje)

Archivo = _reflection.GeneratedProtocolMessageType('Archivo', (_message.Message,), dict(
  DESCRIPTOR = _ARCHIVO,
  __module__ = 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Archivo)
  ))
_sym_db.RegisterMessage(Archivo)

Texto = _reflection.GeneratedProtocolMessageType('Texto', (_message.Message,), dict(
  DESCRIPTOR = _TEXTO,
  __module__ = 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Texto)
  ))
_sym_db.RegisterMessage(Texto)

Usuario = _reflection.GeneratedProtocolMessageType('Usuario', (_message.Message,), dict(
  DESCRIPTOR = _USUARIO,
  __module__ = 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Usuario)
  ))
_sym_db.RegisterMessage(Usuario)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

_ARCHIVO.extensions_by_name['archivo'].message_type = _ARCHIVO
Mensaje.RegisterExtension(_ARCHIVO.extensions_by_name['archivo'])
_TEXTO.extensions_by_name['texto'].message_type = _TEXTO
Mensaje.RegisterExtension(_TEXTO.extensions_by_name['texto'])


_CHAT = _descriptor.ServiceDescriptor(
  name='Chat',
  full_name='Chat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=309,
  serialized_end=391,
  methods=[
  _descriptor.MethodDescriptor(
    name='recibirMensajes',
    full_name='Chat.recibirMensajes',
    index=0,
    containing_service=None,
    input_type=_USUARIO,
    output_type=_MENSAJE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='enviarMensaje',
    full_name='Chat.enviarMensaje',
    index=1,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAT)

DESCRIPTOR.services_by_name['Chat'] = _CHAT

# @@protoc_insertion_point(module_scope)
