# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Chat.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\nChat.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x01\n\x07Mensaje\x12\x11\n\tidMensaje\x18\x01 \x02(\t\x12\x1b\n\tremitente\x18\x02 \x02(\x0b\x32\x08.Usuario\x12.\n\nfechaEnvio\x18\x03 \x02(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tcontenido\x18\x04 \x02(\t*\x04\x08M\x10O\"O\n\x07\x41rchivo\x12\x11\n\tcontenido\x18\x02 \x02(\x0c\x12\x0c\n\x04ruta\x18\x03 \x02(\t2#\n\x07\x61rchivo\x12\x08.Mensaje\x18M \x01(\x0b\x32\x08.Archivo\"L\n\x05Texto\x12\x11\n\tcontenido\x18\x01 \x02(\t\x12\x0f\n\x07\x65\x64itado\x18\x02 \x02(\x08\x32\x1f\n\x05texto\x12\x08.Mensaje\x18N \x01(\x0b\x32\x06.Texto\".\n\x07Usuario\x12\x10\n\x08username\x18\x01 \x02(\t\x12\x11\n\tidUsuario\x18\x02 \x02(\t\"S\n\x0c\x43onversacion\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\x1a\n\x08usuarios\x18\x02 \x03(\x0b\x32\x08.Usuario\x12\x1a\n\x08mensajes\x18\x03 \x03(\x0b\x32\x08.Mensaje\"\x07\n\x05\x45mpty2\x8d\x01\n\x04\x43hat\x12\x33\n\x13iniciarConversacion\x12\r.Conversacion\x1a\r.Conversacion\x12(\n\x0frecibirMensajes\x12\x06.Empty\x1a\r.Conversacion\x12&\n\renviarMensaje\x12\r.Conversacion\x1a\x06.Empty')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_MENSAJE = _descriptor.Descriptor(
  name='Mensaje',
  full_name='Mensaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idMensaje', full_name='Mensaje.idMensaje', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remitente', full_name='Mensaje.remitente', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fechaEnvio', full_name='Mensaje.fechaEnvio', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contenido', full_name='Mensaje.contenido', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(77, 79), ],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=178,
)


_ARCHIVO = _descriptor.Descriptor(
  name='Archivo',
  full_name='Archivo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contenido', full_name='Archivo.contenido', index=0,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ruta', full_name='Archivo.ruta', index=1,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='archivo', full_name='Archivo.archivo', index=0,
      number=77, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=259,
)


_TEXTO = _descriptor.Descriptor(
  name='Texto',
  full_name='Texto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contenido', full_name='Texto.contenido', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='editado', full_name='Texto.editado', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='texto', full_name='Texto.texto', index=0,
      number=78, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=337,
)


_USUARIO = _descriptor.Descriptor(
  name='Usuario',
  full_name='Usuario',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='Usuario.username', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idUsuario', full_name='Usuario.idUsuario', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=385,
)


_CONVERSACION = _descriptor.Descriptor(
  name='Conversacion',
  full_name='Conversacion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Conversacion.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usuarios', full_name='Conversacion.usuarios', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mensajes', full_name='Conversacion.mensajes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=470,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=479,
)

_MENSAJE.fields_by_name['remitente'].message_type = _USUARIO
_MENSAJE.fields_by_name['fechaEnvio'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CONVERSACION.fields_by_name['usuarios'].message_type = _USUARIO
_CONVERSACION.fields_by_name['mensajes'].message_type = _MENSAJE
DESCRIPTOR.message_types_by_name['Mensaje'] = _MENSAJE
DESCRIPTOR.message_types_by_name['Archivo'] = _ARCHIVO
DESCRIPTOR.message_types_by_name['Texto'] = _TEXTO
DESCRIPTOR.message_types_by_name['Usuario'] = _USUARIO
DESCRIPTOR.message_types_by_name['Conversacion'] = _CONVERSACION
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mensaje = _reflection.GeneratedProtocolMessageType('Mensaje', (_message.Message,), dict(
  DESCRIPTOR = _MENSAJE,
  __module__ = 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Mensaje)
  ))
_sym_db.RegisterMessage(Mensaje)

Archivo = _reflection.GeneratedProtocolMessageType('Archivo', (_message.Message,), dict(
  DESCRIPTOR = _ARCHIVO,
  __module__ = 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Archivo)
  ))
_sym_db.RegisterMessage(Archivo)

Texto = _reflection.GeneratedProtocolMessageType('Texto', (_message.Message,), dict(
  DESCRIPTOR = _TEXTO,
  __module__ = 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Texto)
  ))
_sym_db.RegisterMessage(Texto)

Usuario = _reflection.GeneratedProtocolMessageType('Usuario', (_message.Message,), dict(
  DESCRIPTOR = _USUARIO,
  __module__ = 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Usuario)
  ))
_sym_db.RegisterMessage(Usuario)

Conversacion = _reflection.GeneratedProtocolMessageType('Conversacion', (_message.Message,), dict(
  DESCRIPTOR = _CONVERSACION,
  __module__ = 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Conversacion)
  ))
_sym_db.RegisterMessage(Conversacion)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'Chat_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

_ARCHIVO.extensions_by_name['archivo'].message_type = _ARCHIVO
Mensaje.RegisterExtension(_ARCHIVO.extensions_by_name['archivo'])
_TEXTO.extensions_by_name['texto'].message_type = _TEXTO
Mensaje.RegisterExtension(_TEXTO.extensions_by_name['texto'])


_CHAT = _descriptor.ServiceDescriptor(
  name='Chat',
  full_name='Chat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=482,
  serialized_end=623,
  methods=[
  _descriptor.MethodDescriptor(
    name='iniciarConversacion',
    full_name='Chat.iniciarConversacion',
    index=0,
    containing_service=None,
    input_type=_CONVERSACION,
    output_type=_CONVERSACION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='recibirMensajes',
    full_name='Chat.recibirMensajes',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CONVERSACION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='enviarMensaje',
    full_name='Chat.enviarMensaje',
    index=2,
    containing_service=None,
    input_type=_CONVERSACION,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHAT)

DESCRIPTOR.services_by_name['Chat'] = _CHAT

# @@protoc_insertion_point(module_scope)
